language: node_js
node_js:
  - "7"
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
  - npm install
  # - webdriver-manager update 
  # - webdriver-manager start &
  - gulp &
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
# script:
#   - npm test