language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  app: young-fortress-33377
  api_key:
    secure: ctMbzXRMVd01rP8iGlF7/Hf+s52eAOtui3NadWYhP6yugqP78ZTpUgYHiwktl/CoX8AJzebyqT1WGDXTpq2Z2GlSSraSZD2M3X78RO7IESNSDtYCpH/gwV/3pZmDEcw/XRUQmjbd7mrHpsc954kXqpi1CI5bMb5lnHDRuh87507YVGYiwiUueyl7vsm0Noe6dROlonbzxdX3j6xsnxXCsoTn/xOkHEkk5Wkd5KZhpJ5kuvxZsgzDRP5sJxPvtdhzWm/JIiq/ZmTsOylWlVGo3uON32EHBi1czPsndQXGRxvvfY2VCZhP88GbLnszN/Icrtwf04yg1nZ4ljUU8a7eqWkNwQ6JHD/sOBen7E343MdlzSmORUz+DL9J9S67eDXNUVzq6SGdd187ppIKuusa7OeaQ87+Yx1DUcZKIt6+Boll5gfbYy66Xv/JoI1P1R8oB5H1U6MSbVaSDnrLEle/xvsNcwxz2VvSzGUCj3FK2PaRCPdBBNpLKj0EiuzqQz0z5UEZp2iI7FrautsskfOkuWdDiXB8qbHiqoIM8CU7jOWtGWlVPb9FGzaxf2ROIUBKLZ4YiCcF2ylM8FnQAOOXHS9GfxvPxvVLfnffxjvj7rC90cLYHIHTbHwpnSnc++ZECKP4iCV/p3XlcJQS0Eh8WfcLfmw6J5hu3BnTqKz90ZU=
dist: trusty
services: mongodb
addons:
  sauce_connect: true
  chrome: beta
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 10
- npm install
# - "./node_modules/protractor/bin/webdriver-manager update"
# - "./node_modules/protractor/bin/webdriver-manager start > /dev/null 2>&1 &"
- npm start &
- sleep 10
before_install:
- "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu
  --remote-debugging-port=9222 http://localhost &"
env:
  global:
  - secure: DUpXrHNZZJosnHrqs9atumqm3moJUzEY4GLX/pQrgMLrF8LoV/9hY0TDF9GvVHz63LoxHaRcty4nreIM0+GiPwx8t+V5ek3IHZTb4HqPZx/icCUj1/aNgB/lnfN0YmPlPLzbFEspy+cEkXl/pyvVjt+3ebVSbwfGXTapoMfwfNgpFyQ+JLX6NYKS32cfY+3/4yoJOx5G/69VN4jwlI35pOXS1tKaDeFuAYEiMCyyYsm1INONrPUhAuz7p1HgZgidlQtN6WDfD+ZHRJionfPIT6AiLY047/p+TMWoBkXgpEU5PnIyLfC3uTfZ9ouOESWqowDtxc1rYETG1d6QtW2k4W9k2ZBIRE6s9Dem008vY+njSxD9Y4VcMeMOgW9W29Ofn2hDFuXS2KzrcWacEi25WKwEqx2xnrNT6IWBnZzNHfNzTQi3M7yvIzRIg6oGi4fLO7d9a2M2v3VE+w/BPZlp2Hnbra08Rm9o4iRFXpKsiKi29XqT2rw7gwB1Dt9snpPuGUjvZZS5no/wwhTPEYfRsQi8VNWXgqj4xuBqW/nEVS9gucji4/IuNpgZohQNWS8PCCouefnVZIH88MSkhg/JGR2rcNWK7IHj776KLXKFDSX4gus8XHWE7TIuLWeRfC/jtFP/L/gc3gJH7lfXeyEkHzk52JBcGCIvMwHHqjL3O+M=
  - secure: B9Egy7Y95kncA5+FF8x4VKj3lGOywtKh5j/P20u7pCzTW9qDV+VCNyAh39G/8xcUXb46/iiBKzpN7acITLEj/6RYEzbMGjnQIWfHWODt0fXo9up5QUjY/T1wK5wX26rUD8GOF6jpprh2rJ8xpiCPH4Qz5PIEiYGkFM6NqIcvbKak2zsw1k1wsvEu1IJg1wOqtDlWkTVcrMKMaLWebOQUNuQx86BrbmpkSlAiHNVs/JeZ2pTfWBZLy1zm0Ms8ckR//A+mRyPm7xP4jhCR8BfJ118VsshBN6n2C3IJvS8QdwxA+bSvhcujjKpB5wU5AsQKw+uFEuXJsFDurkbXwOb9HNlpfIKMT/TNSMEJBkUIvpOCU0gllnf+P8CVXwuK3f67QzFN4s8zR4fFqHU9fnuLlUUX5kwMFrUgsw1MzFWOJNT97ID8eO0QH/pTprZxGxUhZndPN1HyD0xd7QC4JexxH95pjG8NRsnnioOHX1ce+CN80Z9y+BIQuq7KKFZcsRYbYozfFnpHkKZHQ+84cV6n6uLvEvepH9duhw4jGakgHtzffvz/dEjJtVbrELpBTQn1ltiOBFI1RiehrrOfMidlvDZPgxn+xlcQh2HXWiYlEjPb0RrojcjnehXMXzF+b88f5yUpKytCrExROXjiM9KwVUIaph+JfFpqyNWd4AoWLgc=
  - secure: Pg/DcdGl2/isb1jDzCNfhI9g6t/YjRhnRaifG+mKSq4hcR3vKLnNAzf/k+pP6FLvNzUqCsKQ2R/AG4YPcWXK9Ni5LJuPy8r+bjzy0xf5Bknv7Wtn+1Tsfd77TJX7dPqTho7TM5Mwy5yIL9bmh4mCj0leDrVA1rqCi88YHM7+i8aYE7pB4BOYTpsmHavMXz38OaFbY/A3Py2VVZI5ITd65si4SEqTpQK2FjQ/GDIBWGIqaQtQJ5MgtYQeFjRe0bSUvfyEAle30LmoecK5mQHwZ4PWO20I0wSPn9FmvSYUCDOg1SzMR7TZ45WD23qvilfgN/4N85ufJ/A9GTEWH+YLrIPZAf8wZ8WErbcda8R3eV9LDWKROiPOZ3ntmhdGiHfa8MI8Q0n/lHkr8hWZUPk7dBttPvyi+d2IMydQDbwjAt3GU18glLBVZDoGuMe2swoMEINZJ73vnfBCuE7YKugqjHYktw1y7nneahd3SUmxS2x5GNi2TmTwgi66EmwgBhWPfOjkbo01TlwN/DHWCXA5lk/QQcEnc1mTyXRBv1ckg939SoL58QafA6RxDTBUEjGcTCUPRTNFmL0aMx3kYyxJdyyXW6pR2wbGFIfc/TlrBDpPH79CohXHyYofatcCd3nH17F4KkzMHoeghPckagCQZjo4aOcjWSQjDMNxIY6fjIo=
  - secure: hTQrtF/KcYU40jW41FYVhw/loYPR1GR5thPL5b4UbzNZDLZB4cl18aRmEOAX/lFOopAwq/d4oHilsHdgiPA7OMa69Ny6HWuzIFhy9js3lfQpu3eMD4Ux6FOqKxJyuxIR8Qr6jyjdap8ykFgA29dqWAGYokS4EiOsF6kdf3r0x/kqth6uQ5iXzNznRsJjDVaU3Zie9EuZDnJlgpZ4LS0F2lXyeM9h611kNEXYpP51aiCJsEFzVTy7h70zPYbtLWwvvg6kFeEJOOVXbP67eQIUw35edr6sFOsu/ZbAKENfhmR7HGiomYiV/Om9w3IhPDemcCJ1X5CCPPEOZ9FV8Gi2icGSamGxd5TJ4Y9c72OlvY6sxmvEmtHrEhZna51IyS3dg69foDrQMQW56KkRAcTmN9veQYq9+yNiLImMXHZyM2PZuDBFyM+7Upoe+u9hwdB7QM+WMzizC+7WZHk26qV9vCdMqQ/cn1J9mcXytraR8b1V2QC2WDXZ7he0j8heXRcx9WC/ZlpYW6ikxGTyWa5V09LVM7b8uUTp2+1lHpZ+ARmERX2jbxaHiYekmskB8FaH9pgSjBu+S/fYmtajky0BYIDcXIn6ObdzVBdP4BbzGhzFWyl+ThtV+7ML91f7aox9vRH6R7gd1rE5qrzwC7bxvfgljr1oTU7VecWkZYx/svA=
