language: node_js
node_js:
  - "7"
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
  - npm install
  # - npm install protractor -g 
  # - ./node_modules/protractor/bin/webdriver-manager start > /dev/null 2>&1 &
  -  ./node_modules/protractor/bin/webdriver-manager update
  -  ./node_modules/protractor/bin/webdriver-manager start &
  # - webdriver-manager update 
  # - webdriver-manager start &
  # - gulp &
  - npm start &

# script:
#   - npm test